spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: hh-web-app

  sql:
    init:
      platform: postgres

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/hh_db
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: redis

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/hh-web-app-realm

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    liquibase-schema: hh_db_liquibase_schema
    enabled: false
    contexts: development
    drop-first: false

server:
  port: 7070

jwt:
  token:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

auth:
  white-list:
    - /auth/login
    - /auth/register
    - /auth/refresh
    - /locations/countries
    - /locations/cities
    - /vacancyCategories
    - /files/upload/avatar
    - /error
minio:
  endpoint: http://minio-hh:9000
  accessKey: ${MINIO_ROOT_USER:admin_username}
  secretKey: ${MINIO_ROOT_PASSWORD:adminpassword123}
project:
  upload:
    path:
      default-bucket: java-team
root:
  path: home/files/

app:
  keycloak:
    admin-password: ${KC_BOOTSTRAP_ADMIN_PASSWORD:keycloakAdmin@1234}
    admin-username: ${KC_BOOTSTRAP_KEYCLOAK_ADMIN:keycloakAdmin}
    master-realm: master
    realm: hh-web-app-realm
    keycloak-server-url: http://localhost:8080
    client-id: hh-cli
    admin-client-id: admin-cli
    client-secret: XVFiINeyxTVfW3FSEEzZbN9y8tVGMEmy